#!/usr/bin/env python3
"""
Reasoning team (kimi + gemma4) analyzes Anthropic-Cybersecurity-Skills
to find exact integration points with Raphael 2.0.
"""
import asyncio, json, sys, os
sys.path.insert(0, '.')
from orchestrator.conductor import conductor_call_parallel

RAPHAEL_DOMAIN_MAP = """
Raphael 2.0 has these pipelines and modules:
- orchestrator/scanners/: Recon scanning (nmap, nuclei, whatweb) + SpiderFoot OSINT
- orchestrator/exploit/: Exploit pipeline (SQLi, LFI, upload, ghostcat, mass-assignment)
- orchestrator/postex/: Post-exploitation (lateral movement, privilege escalation)
- orchestrator/proxy_guard.py: OpSec / proxy enforcement (Tor, ProtonVPN)
- orchestrator/anti_forensics.py: Platform-specific cleanup (CentOS, Windows, Tomcat, Oracle, MSSQL)
- orchestrator/brain/: Adaptive brain with episodic memory (SQLite)
- orchestrator/teams.py: Team-based agent workflows (debate, analyze, execute, plan)
- orchestrator/modes/: Deep research, debate, community, RSI, autonomous execution
- orchestrator/phishing/: Phishing pipeline (GoPhish integration)
- orchestrator/exfil/: Exfiltration pipeline
- c2-server/: C2 listener
- sword/: API gateway
- mcp-hub/: MCP server hub
- cloak-service/: Browser automation (Playwright)
- cai-service/: AI model service
"""

SKILLS_CATALOG = """
817 skills across 29 subdomains in /tmp/Anthropic-Cybersecurity-Skills/skills/.
Each skill is a SKILL.md with YAML frontmatter + Markdown workflow.

Key subdomains with skill counts:
- cloud-security: 66 skills
- threat-hunting: 58 skills
- threat-intelligence: 52 skills
- network-security: 43 skills
- web-application-security: 42 skills
- digital-forensics: 41 skills
- malware-analysis: 39 skills
- identity-access-management: 37 skills
- soc-operations: 35 skills
- red-teaming: 33 skills
- container-security: 33 skills
- incident-response: 26 skills
- vulnerability-management: 25 skills
- penetration-testing: 21 skills

Integration mechanism: 
- index.json at root catalogs all 817 skills (name, description, path)
- Each skill has SKILL.md with framework mappings (MITRE ATT&CK, NIST CSF)
- ~120 skills have scripts/agent.py executable
- Some have references/ for deep technical context
- Some have assets/template.md for report templates
"""

PROMPT = RAPHAEL_DOMAIN_MAP + SKILLS_CATALOG + """

TASK: Analyze where the Anthropic-Cybersecurity-Skills library fits into Raphael 2.0.

Specifically:
1. Which Raphael pipelines are MISSING structured skill coverage that this repo provides?
2. Which existing Raphael components could REPLACE their hardcoded logic with a skill lookup?
3. What's the MINIMUM integration path (least code, most impact)?
4. What's the FULL integration path?
5. Which specific skill categories map to which specific Raphael files/line numbers?

Be extremely specific. Reference actual file paths in Raphael 2.0 and actual skill subdomains.
Recommend exactly what to build and what files to change.

Output format:
## Pipeline Gap Analysis
[table: Raphael pipeline | Skills needed | Specific skills from repo]

## Integration Plan
### Phase 1 (minimum)
[concrete steps, files to create/modify]

### Phase 2 (full)
[concrete steps]

## File-by-file Integration Map
[Raphael file path → skills to load → integration type]"""

async def main():
    print("=" * 60)
    print("Reasoning Team — Skills Integration Analysis")
    print("Models: kimi + gemma4 (via conductor with sanitizer)")
    print("=" * 60)

    results = await conductor_call_parallel(
        models=["kimi", "gemma4"],
        prompt=PROMPT,
        category="strategic",
        max_tokens=8192,
        temperature=0.5,
        timeout=300,
        fallback_model="mistral-large",
    )

    for model, text in results.items():
        print(f"\n  {model}: {len(text)} chars")

    combined = "\n\n---\n\n".join(f"## {m}\n\n{t}" for m, t in results.items())
    
    with open("skills_integration_analysis.json", "w") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    with open("skills_integration_report.md", "w") as f:
        f.write("# Skills Integration Analysis\n\n")
        f.write(f"Generated by reasoning team (kimi + gemma4 via conductor)\n\n")
        f.write(combined)

    print(f"\n{'='*60}")
    print(f"Saved to skills_integration_report.md")
    print(f"{'='*60}")

    # Print the analysis
    for model, text in results.items():
        print(f"\n\n=== {model.upper()} ===\n")
        print(text[:3000])
        if len(text) > 3000:
            print(f"\n... (truncated, see skills_integration_report.md)")

if __name__ == "__main__":
    asyncio.run(main())
