services:
  www-flask:
    build: ./vulnu-pieces/www
    container_name: vulnu-www-flask
    ports:
      - "8081:5000"
    networks:
      - vulnu-net

  ums-flask:
    build: ./vulnu-pieces/ums
    container_name: vulnu-ums-flask
    ports:
      - "8082:5001"
    networks:
      - vulnu-net

  mysql:
    image: mysql:5.7
    container_name: vulnu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vulnu_cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cms123
    volumes:
      - ./databases/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vulnu-net
    ports:
      - "3306:3306"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: vulnu-mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Training123!
    volumes:
      - ./databases/mssql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vulnu-net
    ports:
      - "1433:1433"

  nertu:
    build: ./services/nertu
    container_name: vulnu-nertu
    ports:
      - "8083:8080"
      - "8009:8009"
    environment:
      - ORACLE_HOST=oracle
    networks:
      - vulnu-net
    depends_on:
      - oracle

  oracle:
    image: gvenzl/oracle-xe:21
    container_name: vulnu-oracle
    environment:
      ORACLE_PASSWORD: oracle
    networks:
      - vulnu-net
    ports:
      - "1521:1521"

networks:
  vulnu-net:
    driver: bridge
