import json
import logging
import os
import time
from datetime import datetime
from typing import Optional

from orchestrator.brain.phases.models import Finding, PhaseResult, Severity

logger = logging.getLogger("phase_reporting")


REPORTS_DIR = os.getenv("RAPHAEL_REPORTS_DIR", "/tmp/raphael_reports")


def _ensure_reports_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def _timestamp() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")


def _generate_markdown(target: str, findings: list[Finding], summary: str) -> str:
    lines = []
    lines.append(f"# Raphael Autonomous Security Assessment Report")
    lines.append(f"")
    lines.append(f"**Target:** `{target}`")
    lines.append(f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Summary:** {summary}")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    by_severity = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
    for f in findings:
        by_severity.setdefault(f.severity.value, []).append(f)

    for sev_label in ["critical", "high", "medium", "low", "info"]:
        items = by_severity.get(sev_label, [])
        if not items:
            continue
        lines.append(f"## {sev_label.upper()} — {len(items)} finding(s)")
        lines.append(f"")
        for f in items:
            lines.append(f"### {f.type}")
            lines.append(f"")
            lines.append(f"- **Phase:** {f.phase}")
            lines.append(f"- **Host:** {f.host or 'N/A'}")
            lines.append(f"- **Port:** {f.port or 'N/A'}")
            lines.append(f"- **Service:** {f.service or 'N/A'}")
            lines.append(f"- **Description:** {f.description}")
            if f.evidence:
                lines.append(f"- **Evidence:** `{f.evidence[:300]}`")
            if f.cve:
                lines.append(f"- **CVE:** {f.cve}")
            if f.payload:
                lines.append(f"- **Payload:** `{f.payload[:200]}`")
            lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

    lines.append(f"*Report generated by Raphael 2.0 Autonomous AI Security Platform*")
    return "\n".join(lines)


def _generate_html(target: str, findings: list[Finding], summary: str) -> str:
    html_parts = ["<html><head><meta charset='utf-8'><title>Raphael Report</title>"]
    html_parts.append("<style>body{font-family: sans-serif; max-width: 900px; margin: 2em auto; ")
    html_parts.append("padding: 0 1em; line-height: 1.6; background: #0d1117; color: #c9d1d9;}")
    html_parts.append("h1{color: #58a6ff;} h2{border-bottom:1px solid #30363d; padding-bottom:.3em;}")
    html_parts.append(".critical{color:#f85149;} .high{color:#d29922;} ")
    html_parts.append(".medium{color:#58a6ff;} .low{color:#8b949e;} ")
    html_parts.append("code{background:#161b22; padding:.2em .4em; border-radius:4px;}")
    html_parts.append("pre{background:#161b22; padding:1em; border-radius:6px; overflow-x:auto;}")
    html_parts.append("</style></head><body>")
    html_parts.append(f"<h1>Raphael Security Report: {target}</h1>")
    html_parts.append(f"<p><strong>Date:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>")
    html_parts.append(f"<p><strong>Summary:</strong> {summary}</p><hr>")

    by_severity = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
    for f in findings:
        by_severity.setdefault(f.severity.value, []).append(f)

    for sev_label in ["critical", "high", "medium", "low", "info"]:
        items = by_severity.get(sev_label, [])
        if not items:
            continue
        html_parts.append(f"<h2 class='{sev_label}'>{sev_label.upper()} — {len(items)}</h2>")
        for f in items:
            html_parts.append(f"<h3>{f.type}</h3><ul>")
            html_parts.append(f"<li><strong>Phase:</strong> {f.phase}</li>")
            html_parts.append(f"<li><strong>Host:</strong> {f.host or 'N/A'}</li>")
            html_parts.append(f"<li><strong>Port:</strong> {f.port or 'N/A'}</li>")
            html_parts.append(f"<li><strong>Description:</strong> {f.description}</li>")
            if f.evidence:
                html_parts.append(f"<li><strong>Evidence:</strong> <code>{f.evidence[:300]}</code></li>")
            if f.cve:
                html_parts.append(f"<li><strong>CVE:</strong> {f.cve}</li>")
            html_parts.append("</ul>")
        html_parts.append("<hr>")

    html_parts.append("<p><em>Raphael 2.0 Autonomous AI Security Platform</em></p>")
    html_parts.append("</body></html>")
    return "\n".join(html_parts)


def _generate_json(target: str, findings: list[Finding], summary: str) -> str:
    data = {
        "report": {
            "target": target,
            "timestamp": datetime.utcnow().isoformat(),
            "summary": summary,
            "findings_count": len(findings),
        },
        "findings": [f.to_dict() for f in findings],
    }
    return json.dumps(data, indent=2)


async def run_reporting(target: str, findings: list[Finding] = None) -> PhaseResult:
    t0 = time.time()
    all_findings = list(findings or [])
    errors = []

    _ensure_reports_dir()
    ts = _timestamp()
    safe_target = target.replace(":", "_").replace("/", "_").replace(".", "_")

    summary = f"Raphael assessment of {target}: {len(all_findings)} total findings"

    report_data = {
        "markdown": _generate_markdown(target, all_findings, summary),
        "html": _generate_html(target, all_findings, summary),
        "json": _generate_json(target, all_findings, summary),
    }

    paths = {}
    for fmt, content in report_data.items():
        ext = fmt if fmt != "markdown" else "md"
        path = os.path.join(REPORTS_DIR, f"{safe_target}_{ts}.{ext}")
        try:
            with open(path, "w") as f:
                f.write(content)
            paths[fmt] = path
            logger.info(f"Report written: {path}")
        except Exception as e:
            errors.append(f"{fmt}:{e}")

    all_findings.append(Finding(
        phase="reporting", type="report_generated", target=target,
        severity=Severity.INFO,
        description=f"Reports generated for {target}",
        evidence=f"formats: {', '.join(paths.keys())} | dir: {REPORTS_DIR}",
        raw=paths,
    ))

    latency = time.time() - t0
    return PhaseResult(
        phase="reporting",
        success=len(paths) > 0,
        findings=all_findings,
        summary=summary,
        latency=latency,
        error="; ".join(errors) if errors else None,
    )


async def run_generate_report(target: str, findings: list[Finding] = None) -> PhaseResult:
    return await run_reporting(target, findings)