events {}
http {
    upstream www {
        server www:80;
    }
    upstream www-flask {
        server www-flask:5000;
    }
    upstream ums {
        server ums-flask:5001;
    }
    upstream nertu {
        server nertu:8080;
    }

    server {
        listen 80;
        server_name www.vulnu-lab.local ums.vulnu-lab.local nertu.vulnu-lab.local;

        location /www/ { proxy_pass http://www/; }
        location /api/ { proxy_pass http://www-flask/; }
        location /ums/ { proxy_pass http://ums-flask/; }
        location /nertu/ { proxy_pass http://nertu/; }
    }
}