import json, os
from datetime import datetime

class SwordReport:
    def __init__(self, results: dict):
        self.results = results
        self.target = results.get("target", "unknown")
        self.timestamp = datetime.utcnow().strftime("%Y-%m-%d_%H-%M-%S")

    def generate_markdown(self) -> str:
        lines = []
        lines.append(f"# Sword Offensive Report — {self.target}")
        lines.append(f"**Generated:** {self.timestamp}")
        lines.append(f"**Phases:** {', '.join(self.results.get('phases_completed', []))}")
        lines.append("")
        lines.append("## Summary")
        lines.append(self.results.get("summary", "No summary"))
        lines.append("")

        for phase_name in ["recon", "scan", "exploit", "postex", "exfil", "phish"]:
            phase = self.results.get(phase_name)
            if not phase:
                continue
            lines.append(f"## Phase: {phase_name.upper()}")
            if "error" in phase:
                lines.append(f"**Error:** {phase['error']}")
                lines.append("")
                continue
            for key, value in phase.items():
                if key == "summary":
                    lines.append(f"**Summary:** {value}")
                elif key in ("target", "target_ip", "method") or key.endswith("_count"):
                    lines.append(f"- **{key}:** {value}")
                elif isinstance(value, dict):
                    lines.append(f"- **{key}:** {len(value)} items")
                elif isinstance(value, list):
                    lines.append(f"- **{key}:** {len(value)} items")
                elif isinstance(value, str) and len(value) > 200:
                    lines.append(f"- **{key}:** (truncated, {len(value)} chars)")
                else:
                    lines.append(f"- **{key}:** {value}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Report auto-generated by Raphael 2.0 Sword Pipeline*")
        return "\n".join(lines)

    def generate_html(self) -> str:
        md = self.generate_markdown()
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sword Report — {self.target}</title>
<style>
body {{ font-family: 'Courier New', monospace; background: #0a0a0a; color: #00ff00; padding: 20px; }}
h1 {{ color: #ff4444; border-bottom: 2px solid #ff4444; }}
h2 {{ color: #ffaa00; margin-top: 30px; }}
pre {{ background: #111; padding: 10px; border-left: 3px solid #00ff00; }}
.summary {{ background: #1a1a2e; padding: 15px; border-radius: 5px; }}
.error {{ color: #ff0000; }}
.meta {{ color: #888; }}
</style>
</head>
<body>
<pre>{md}</pre>
</body>
</html>"""
        return html

    def save(self, directory: str = "/tmp/sword_reports"):
        os.makedirs(directory, exist_ok=True)
        safe_target = self.target.replace("://", "_").replace("/", "_").replace(":", "_")
        base = os.path.join(directory, f"sword_{safe_target}_{self.timestamp}")

        md_path = base + ".md"
        with open(md_path, "w") as f:
            f.write(self.generate_markdown())

        html_path = base + ".html"
        with open(html_path, "w") as f:
            f.write(self.generate_html())

        json_path = base + ".json"
        with open(json_path, "w") as f:
            json.dump(self.results, f, indent=2, default=str)

        return {"markdown": md_path, "html": html_path, "json": json_path}
